volumes:
  open-webui:
  neo4j_data:
  neo4j_logs:

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    container_name: open-webui
    expose:
      - 8080/tcp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data

  graphiti:
    extends:
      file: ./graphiti/mcp_server/docker-compose.yml
      service: graphiti-mcp-neo4j

  neo4j:
    extends:
      file: ./graphiti/mcp_server/docker-compose.yml
      service: neo4j