name: Evaluate Baseline+VDB

permissions:
  contents: read

on:
  push:
    branches:
      - evaluate_baseline_vdb

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

defaults:
  run:
    shell: bash

jobs:
  evaluate-baseline-vdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Dependencies
        run: uv sync --all-groups
        working-directory: memory_agents

      - name: Generate Encryption Key
        run: openssl rand -hex 32 > encryption_key.txt
        working-directory: .

      - name: Set Encryption Key
        run: export ENCRYPTION_KEY=$(cat encryption_key.txt)
        working-directory: .

      - name: Evaluate Baseline+VDB
        run: uv run answer_generation_and_evaluation.py --agent baseline_vdb
        working-directory: memory_agents/longmemeval

        
