name: Evaluate Baseline+Graphiti+VDB

permissions:
  contents: read

on:
  push:
    branches:
      - evaluate_graphiti_vdb

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

defaults:
  run:
    shell: bash

jobs:
  evaluate-graphiti-vdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Dependencies
        run: uv sync --all-groups
        working-directory: memory_agents

      - name: Generate Encryption Key
        run: openssl rand -hex 32 > encryption_key.txt
        working-directory: .

      - name: Set Encryption Key
        run: export ENCRYPTION_KEY=$(cat encryption_key.txt)
        working-directory: .

      - name: Run Docker
        run: docker compose -f docker-compose-workflow.yml up -d
        working-directory: .

      - name: Wait for services to start
        run: |
          name=$(docker compose ps graphiti --format '{{.Name}}')
          until [ "$(docker inspect -f '{{.State.Health.Status}}' $name)" = "healthy" ]; do
            sleep 1
          done

      - name: Evaluate Baseline+Graphiti+VDB
        run: uv run answer_generation_and_evaluation.py --agent graphiti_vdb
        working-directory: memory_agents/longmemeval

        
